_BASE_: "Base-SimpleBaseline.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/torchvision/R-50.pkl"
  BACKBONE:
    NAME: "build_resnet_backbone"
  RESNETS:
    DEPTH: 50
    STRIDE_IN_1X1: False
    OUT_FEATURES: ["res5"]
    RES5_DILATION: 2
  ROI_HEADS:
    IN_FEATURES: ["res5"]
  ROI_BOX_HEAD:
    POOLER_TYPE: "ROIAlignV2"
    POOLER_RESOLUTION: 7
    POOLER_SAMPLING_RATIO: 2
  SimpleBaseline:
    NUM_QUERIES: 100
    NUM_CLASSES: 80
    USE_FPN: False
DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST:  ("coco_2017_val",)
SOLVER:
  STEPS: (220000,)
  MAX_ITER: 280000
INPUT:
  CROP:
    ENABLED: False
  FORMAT: "RGB"
